### PR TITLE
Rewrite and finalize Steuerung page

### LINKED ISSUE #55: Finalise Steuerung page
- [x] Complete the entries about different running / walking modes (see "TODO")
- [x] proof read
- [x] fix the width of the markdown table being too narrow

Thanks.

### PR DESCRIPTION
**Pull request by LeonTReal**
Restructured and finalized the page.

Open for review after:
- [x] Update key binds
- [x] create layout switcher
  - [x] add windows layouts
  - [x] add mac layouts
- [x] make preferred layout persistent
~~style layout selector~~ moved to #66 

closes #55

### CODE REVIEW

**Comment by pantoffelemmy** [comment]
@LeonTReal @Venrix With my last commit 42a59ee4306782eee277af30838a276c98682661 I made some changes to the `Keys` component which are documented in the `README.md`. tl;dr: from now on use english identifiers in the `keys=""` prop, i.e. ctrl instead of strg for example.

**Comment by pantoffelemmy** [comment]
The preferred keys presentation (german/english and windows/mac keys) is now persistent across pages based on the most recent choice on the steuerung page. If you want to see that in action, go to the [Sanitäter](https://rewrite-steuerung--tfhcwiki.netlify.app/articles/sanitaetsdienst/sanitaeter) page, scroll to the bottom and notice how its german. Go to [Steuerung](https://rewrite-steuerung--tfhcwiki.netlify.app/articles/ausbildung/steuerung) and switch to english using the dropdown menu. Go back and enjoy it being english now. :)

The mapings for mac keys are now implemented yet, that needs to be addressed before merging.
Also, the dropdown I created on the page was just for debugging purposes and is not exactly eye candy, maybe @Venrix could come up with a nice selector. It's just important that the `on:input` function is carried over, because that is where the preference is updated. I could also imagine having them replaced with two independent selectors, one for the OS and one for language.

**Review by pantoffelemmy — APPROVED** [review]
Since I've authored much of this myself a second opinion might be good. @LeonTReal please decide the time of merging.

**Comment by LeonTReal** [comment]
@pantoffelemmy I added the wip banner to the page, since some styling changes are yet to be done.

**Pull request merged**
